# Generated by Django 5.2.17 on 2026-09-17 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MagazineIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "issue_number",
                    models.CharField(help_text="e.g. 'Issue 118'", max_length=40),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'October / November 2026'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_digital_available", models.BooleanField(default=True)),
                (
                    "digital_file",
                    models.FileField(
                        blank=True, null=True, upload_to="magazine_issues/"
                    ),
                ),
                ("is_print_available", models.BooleanField(default=True)),
                ("print_sku", models.CharField(blank=True, max_length=60)),
                ("print_sold_out", models.BooleanField(default=False)),
                ("publish_date", models.DateField()),
                (
                    "is_current_issue",
                    models.BooleanField(
                        default=False,
                        help_text="Only one issue should be current at a time.",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Captured even for guest checkout.", max_length=254
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total, in GHS.", max_digits=10
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_link",
                    models.URLField(
                        blank=True,
                        help_text="Signed digital-download link, set once payment is confirmed.",
                    ),
                ),
                (
                    "shipping_address",
                    models.TextField(
                        blank=True, help_text="Required only for print items."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("digital", "Digital"), ("print", "Print")],
                        default="digital",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price at time of purchase, not the issue's current price.",
                        max_digits=8,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="magazine.magazineissue",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="magazine.order",
                    ),
                ),
            ],
        ),
    ]
