# Generated by Django 5.2.17 on 2026-09-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="paystack_reference",
            new_name="stripe_session_id",
        ),
    ]
