# Generated by Django 5.2.17 on 2026-09-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0002_rename_paystack_reference_order_stripe_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_link",
        ),
    ]
