# Generated by Django 5.2.17 on 2026-09-24 16:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magazine", "0003_remove_order_delivery_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="magazine.order",
            ),
        ),
    ]
