# Generated by Django 5.2.17 on 2026-09-17 11:31

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0098_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=60, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="event_videos/"),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "event_tag",
                    models.CharField(
                        blank=True,
                        help_text="Free-text tag, e.g. 'GAFW 2026' — lets a gallery be filtered without a hard FK.",
                        max_length=120,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                (
                    "dek",
                    models.CharField(
                        blank=True,
                        help_text="One-sentence summary shown on cards and below the headline.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("paragraph", 0), ("image", 1), ("quote", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["bold", "italic", "link", "ol", "ul"]},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 2), ("attribution", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("author_name", models.CharField(blank=True, max_length=120)),
                ("published_date", models.DateField(blank=True, null=True)),
                (
                    "read_time_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PostIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.WAGTAIL_PAGE_MODEL,
                    ),
                ),
                ("intro", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
