# Generated by Django 5.2.17 on 2026-09-29 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
        ('events', '0003_rename_paystack_reference_ticket_stripe_session_id'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('publication', models.CharField(max_length=150)),
                ('article_url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('published_date', models.DateField()),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_visible', models.BooleanField(default=False, help_text='Show this article on the Media page.')),
            ],
            options={
                'verbose_name': 'press coverage',
                'verbose_name_plural': 'press coverage',
                'ordering': ['display_order', '-published_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='HTTPS YouTube or public Vimeo link. Use either a link or an uploaded video.')),
                ('video_file', models.FileField(blank=True, help_text='MP4 or WebM. Leave the video link empty when uploading a file.', upload_to='media_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])])),
                ('duration', models.CharField(blank=True, help_text='Optional duration, e.g. 6:42 or 1:06:42.', max_length=12, validators=[django.core.validators.RegexValidator('^(?:\\d+:)?\\d{1,2}:[0-5]\\d$', 'Use m:ss or h:mm:ss.')])),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_visible', models.BooleanField(default=False, help_text='Show this video on the Media page.')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='events.event')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', '-pk'],
            },
        ),
    ]
