# Generated by Django 5.2.17 on 2026-09-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_presscoverage_video'),
        ('events', '0003_rename_paystack_reference_ticket_stripe_session_id'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alt_text', models.CharField(help_text='Describe the image for visitors using screen readers.', max_length=250)),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_visible', models.BooleanField(default=False, help_text='Show this photo on the Media page.')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='events.event')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_photos', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', '-pk'],
            },
        ),
    ]
