# Generated by Django 5.2.17 on 2026-09-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['display_order', '-pk'], 'verbose_name': 'media gallery item', 'verbose_name_plural': 'Media Gallery'},
        ),
    ]
