# Generated by Django 5.2.17 on 2026-09-30 12:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_photo_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('button_label', models.CharField(default='Explore', max_length=60)),
                ('button_path', models.CharField(default='/events', help_text='A site path, e.g. /events/gafw', max_length=250)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('video', models.ForeignKey(blank=True, help_text='Choose a visible video with an uploaded MP4/WebM for background playback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_slides', to='content.video')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https', 'http'])])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=False)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
