# Generated by Django 5.2.17 on 2026-09-29 12:19

import apps.submissions.models
import apps.submissions.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_rename_paystack_reference_ticket_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-consent_at'],
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('open_call', models.CharField(choices=[('designers', 'GAFW Young Designers Showcase'), ('honours', 'Ghana Women of the Year — Nominate an Honouree'), ('style', 'Glitz Style Awards — Reader Nomination')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_link', models.URLField(blank=True)),
                ('portfolio_file', models.FileField(blank=True, storage=apps.submissions.storage.PortfolioStorage(), upload_to=apps.submissions.models.portfolio_path)),
                ('statement', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('not_selected', 'Not selected')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes; not sent to the applicant.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('general', 'General enquiry'), ('event', 'Event interest'), ('sponsorship', 'Sponsorship enquiry')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Private staff notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
